/* translate fm-violin in /Users/jerometruong/.emacs.d/lisp/clm-4/v.ins to C
 *   written Mon 17-Sep-12 at 11:44 by CLM of 21-Mar-12
 */

#include <mus-config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <math.h>
#include <signal.h>
#include <cmus.h>

static sig_atomic_t got_sigint = 0; /* catch C-C if hung */
static void sig_err(int sig) {got_sigint = sig;}

int clm_fm_violin (double *clm_double, int datar_len, int *clm_int, int datai_len)
{
  /* The _clm_* variables are temporary values generated by the run macro */
  void (*old_SIGINT)(int);
  mus_long_t I;
  bool _clm_59, _clm_55, MODULATE, EASY_CASE, FROBBER;
  double _clm_114, _clm_113, _clm_112, _clm_111, _clm_110, _clm_109, _clm_108, _clm_107, _clm_106, _clm_105, _clm_104, _clm_103, _clm_102, _clm_101, _clm_100, _clm_99, _clm_98, _clm_97, _clm_96, _clm_95, _clm_94, _clm_93, _clm_91, _clm_90, _clm_89, _clm_88, _clm_80, _clm_79, _clm_74, _clm_73, _clm_68, _clm_67, _clm_66, _clm_65, _clm_63, _clm_61, VIB, FM3_RAT, FM2_RAT, FM1_RAT, MODULATION, AMP_FUZZ, IND_FUZZ, FUZZ, NOISE_AMOUNT;
  double *COEFFS = NULL;
  mus_any *CARRIER = NULL, *AMPF = NULL, *LOC = NULL, *FMOSC3 = NULL, *INDF3 = NULL, *FMOSC2 = NULL, *INDF2 = NULL, *FMOSC1 = NULL, *INDF1 = NULL, *RANVIB = NULL, *PERVIB = NULL, *FRQF = NULL, *FRB_ENV = NULL, *FM_NOI = NULL, *AMP_NOI = NULL, *IND_NOI = NULL;
  void *all_gens = NULL;
  mus_long_t clm_beg, clm_end;
  
  all_gens = clm_make_genbag();
  clm_beg = clm_to_mus_long_t(clm_int, 1);
  clm_end = clm_to_mus_long_t(clm_int, 3);
  I = clm_int[39];
  NOISE_AMOUNT = clm_double[17];
  FUZZ = clm_double[18];
  IND_FUZZ = clm_double[19];
  AMP_FUZZ = clm_double[20];
  MODULATION = clm_double[21];
  FM1_RAT = clm_double[22];
  FM2_RAT = clm_double[23];
  FM3_RAT = clm_double[24];
  VIB = clm_double[25];
  if (CLM_RAND_INTERP_P(7))
    IND_NOI = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_interp_with_distribution(
        clm_double[CLM_RLOC(7)],
        clm_double[CLM_RLOC(7) + 1],
        (clm_int[CLM_ILOC(7) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(7) + 2)) : NULL,
        clm_int[CLM_ILOC(7) + 2]));
  if (CLM_RAND_INTERP_P(9))
    AMP_NOI = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_interp_with_distribution(
        clm_double[CLM_RLOC(9)],
        clm_double[CLM_RLOC(9) + 1],
        (clm_int[CLM_ILOC(9) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(9) + 2)) : NULL,
        clm_int[CLM_ILOC(9) + 2]));
  if (CLM_VAR_TYPE(41) != CLM_NO_TYPE) COEFFS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(41)));
  FROBBER = (bool)clm_int[43];
  EASY_CASE = (bool)clm_int[45];
  MODULATE = (bool)clm_int[47];
  if (CLM_RAND_P(11))
    FM_NOI = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_with_distribution(
        clm_double[CLM_RLOC(11)],
        clm_double[CLM_RLOC(11) + 1],
        (clm_int[CLM_ILOC(11) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(11) + 2)) : NULL,
        clm_int[CLM_ILOC(11) + 2]));
  if (CLM_ENV_P(13))
    FRB_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(13) + 3), /* breakpoints */
        clm_int[CLM_ILOC(13) + 2], /* num points */
        clm_double[CLM_RLOC(13) + 1], /* scaler */
        clm_double[CLM_RLOC(13) + 2], /* offset */
        clm_double[CLM_RLOC(13)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(13) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(15))
    FRQF = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(15) + 3), /* breakpoints */
        clm_int[CLM_ILOC(15) + 2], /* num points */
        clm_double[CLM_RLOC(15) + 1], /* scaler */
        clm_double[CLM_RLOC(15) + 2], /* offset */
        clm_double[CLM_RLOC(15)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(15) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_TRIANGLE_WAVE_P(17))
    PERVIB = clm_add_gen_to_genbag(all_gens, 
      mus_make_triangle_wave(
        mus_radians_to_hz(clm_double[CLM_RLOC(17)]),
        clm_double[CLM_RLOC(17) + 2],
        clm_double[CLM_RLOC(17) + 1]));
  if (CLM_RAND_INTERP_P(19))
    RANVIB = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_interp_with_distribution(
        clm_double[CLM_RLOC(19)],
        clm_double[CLM_RLOC(19) + 1],
        (clm_int[CLM_ILOC(19) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(19) + 2)) : NULL,
        clm_int[CLM_ILOC(19) + 2]));
  if (CLM_ENV_P(21))
    INDF1 = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(21) + 3), /* breakpoints */
        clm_int[CLM_ILOC(21) + 2], /* num points */
        clm_double[CLM_RLOC(21) + 1], /* scaler */
        clm_double[CLM_RLOC(21) + 2], /* offset */
        clm_double[CLM_RLOC(21)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(21) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_OSCIL_P(23))
    FMOSC1 = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(23)]),
        clm_double[CLM_RLOC(23) + 1]));
  if (CLM_ENV_P(25))
    INDF2 = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(25) + 3), /* breakpoints */
        clm_int[CLM_ILOC(25) + 2], /* num points */
        clm_double[CLM_RLOC(25) + 1], /* scaler */
        clm_double[CLM_RLOC(25) + 2], /* offset */
        clm_double[CLM_RLOC(25)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(25) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_OSCIL_P(27))
    FMOSC2 = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(27)]),
        clm_double[CLM_RLOC(27) + 1]));
  if (CLM_ENV_P(29))
    INDF3 = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(29) + 3), /* breakpoints */
        clm_int[CLM_ILOC(29) + 2], /* num points */
        clm_double[CLM_RLOC(29) + 1], /* scaler */
        clm_double[CLM_RLOC(29) + 2], /* offset */
        clm_double[CLM_RLOC(29)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(29) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_OSCIL_P(31))
    FMOSC3 = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(31)]),
        clm_double[CLM_RLOC(31) + 1]));
  if (CLM_LOCSIG_P(33))
    LOC = clm_add_gen_to_genbag(all_gens, 
      mus_make_locsig(
        clm_double[CLM_RLOC(33)],
        clm_double[CLM_RLOC(33) + 1],
        clm_double[CLM_RLOC(33) + 2],
        clm_int[CLM_ILOC(33) + 2],
        clm_output(), (clm_reverb()) ? mus_channels(clm_reverb()) : 0, clm_reverb(),
        clm_int[CLM_ILOC(33) + 3]));
  if (CLM_ENV_P(35))
    AMPF = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(35) + 3), /* breakpoints */
        clm_int[CLM_ILOC(35) + 2], /* num points */
        clm_double[CLM_RLOC(35) + 1], /* scaler */
        clm_double[CLM_RLOC(35) + 2], /* offset */
        clm_double[CLM_RLOC(35)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(35) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_OSCIL_P(37))
    CARRIER = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(37)]),
        clm_double[CLM_RLOC(37) + 1]));
  if (clm_beg > clm_end) return(1);
  got_sigint = 0; old_SIGINT = clm_signal(SIGINT, sig_err);                     /* trap SIGINT */
  I = clm_beg;                                                                  /* pass counter */

SAMPLE_LOOP_BEGIN:
  if (got_sigint != 0) {clm_int[0] = (int)got_sigint; goto RUN_ALL_DONE;}
  if (I > clm_end) {I = clm_end; goto RUN_ALL_DONE;}
                                                                                /* (progn */
                                                                                /* (if (/= 0.0 noise-amount) */
  _clm_55 = (0.0 != NOISE_AMOUNT);                                              /* (neq 0.0 NOISE-AMOUNT) */
  if ((!_clm_55)) goto L_53;
                                                                                /* (if (null frobber) */
  _clm_59 = (!FROBBER);                                                         /* (null FROBBER) */
  if ((!_clm_59)) goto L_57;
  _clm_61 = mus_rand(FM_NOI, 0.0);
  FUZZ = _clm_61;                                                               /* (setf FUZZ _clm_61) */
  goto L_58;
L_57:
  _clm_63 = mus_env(FRB_ENV);                                                   /* (env FRB-ENV) */
  FUZZ = _clm_63;                                                               /* (setf FUZZ _clm_63) */
L_58:
  goto L_54;
L_53:
L_54:
  _clm_66 = mus_env(FRQF);                                                      /* (env FRQF) */
  _clm_67 = mus_triangle_wave(PERVIB, 0.0);                                     /* (triangle-wave PERVIB) */
  _clm_68 = mus_rand_interp(RANVIB, 0.0);
                                                                                /* (+ _clm_66 _clm_67 _clm_68) */
  _clm_65 = ((_clm_66) + (_clm_67) + (_clm_68));
  VIB = _clm_65;                                                                /* (setf VIB _clm_65) */
                                                                                /* (if ind-noi */
  if ((!IND_NOI)) goto L_70;
  _clm_74 = mus_rand_interp(IND_NOI, 0.0);
                                                                                /* (+ 1.0 _clm_74) */
  _clm_73 = ((1.0) + (_clm_74));
  IND_FUZZ = _clm_73;                                                           /* (setf IND-FUZZ _clm_73) */
  goto L_71;
L_70:
L_71:
                                                                                /* (if amp-noi */
  if ((!AMP_NOI)) goto L_76;
  _clm_80 = mus_rand_interp(AMP_NOI, 0.0);
                                                                                /* (+ 1.0 _clm_80) */
  _clm_79 = ((1.0) + (_clm_80));
  AMP_FUZZ = _clm_79;                                                           /* (setf AMP-FUZZ _clm_79) */
  goto L_77;
L_76:
L_77:
                                                                                /* (if modulate */
  if ((!MODULATE)) goto L_82;
                                                                                /* (if easy-case */
  if ((!EASY_CASE)) goto L_85;
  _clm_89 = mus_env(INDF1);                                                     /* (env INDF1) */
  _clm_91 = mus_oscil_fm(FMOSC1, VIB);                                          /* (oscil FMOSC1 VIB) */
  _clm_90 = mus_polynomial(COEFFS, _clm_91, CLM_ARR_SIZE(CLM_VAR_ADDR(41)));
                                                                                /* (* _clm_89 _clm_90) */
  _clm_88 = ((_clm_89) * (_clm_90));
  MODULATION = _clm_88;                                                         /* (setf MODULATION _clm_88) */
  goto L_86;
L_85:
  _clm_95 = mus_env(INDF1);                                                     /* (env INDF1) */
                                                                                /* (* fm1-rat vib) */
  _clm_98 = ((FM1_RAT) * (VIB));
                                                                                /* (+ _clm_98 fuzz) */
  _clm_97 = ((_clm_98) + (FUZZ));
  _clm_96 = mus_oscil_fm(FMOSC1, _clm_97);                                      /* (oscil FMOSC1 _clm_97) */
                                                                                /* (* _clm_95 _clm_96) */
  _clm_94 = ((_clm_95) * (_clm_96));
  _clm_100 = mus_env(INDF2);                                                    /* (env INDF2) */
                                                                                /* (* fm2-rat vib) */
  _clm_103 = ((FM2_RAT) * (VIB));
                                                                                /* (+ _clm_103 fuzz) */
  _clm_102 = ((_clm_103) + (FUZZ));
  _clm_101 = mus_oscil_fm(FMOSC2, _clm_102);                                    /* (oscil FMOSC2 _clm_102) */
                                                                                /* (* _clm_100 _clm_101) */
  _clm_99 = ((_clm_100) * (_clm_101));
  _clm_105 = mus_env(INDF3);                                                    /* (env INDF3) */
                                                                                /* (* fm3-rat vib) */
  _clm_108 = ((FM3_RAT) * (VIB));
                                                                                /* (+ _clm_108 fuzz) */
  _clm_107 = ((_clm_108) + (FUZZ));
  _clm_106 = mus_oscil_fm(FMOSC3, _clm_107);                                    /* (oscil FMOSC3 _clm_107) */
                                                                                /* (* _clm_105 _clm_106) */
  _clm_104 = ((_clm_105) * (_clm_106));
                                                                                /* (+ _clm_94 _clm_99 _clm_104) */
  _clm_93 = ((_clm_94) + (_clm_99) + (_clm_104));
  MODULATION = _clm_93;                                                         /* (setf MODULATION _clm_93) */
L_86:
  goto L_83;
L_82:
L_83:
  _clm_111 = mus_env(AMPF);                                                     /* (env AMPF) */
                                                                                /* (* ind-fuzz modulation) */
  _clm_114 = ((IND_FUZZ) * (MODULATION));
                                                                                /* (+ vib _clm_114) */
  _clm_113 = ((VIB) + (_clm_114));
  _clm_112 = mus_oscil_fm(CARRIER, _clm_113);                                   /* (oscil CARRIER _clm_113) */
                                                                                /* (* _clm_111 amp-fuzz _clm_112) */
  _clm_110 = ((_clm_111) * (AMP_FUZZ) * (_clm_112));
  _clm_109 = clm_locsig(LOC, I, _clm_110);
  I++;                                                                          /* increment pass counter and loop */
goto SAMPLE_LOOP_BEGIN;

RUN_ALL_DONE:
  clm_signal(SIGINT,old_SIGINT);
  if (all_gens) clm_free_genbag(all_gens);

  return(1);
}

