;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-semi&comma
        c-indent-line-or-region
        dabbrev-expand
        end-of-visual-line
        isearch-forward-regexp
        isearch-other-control-char
        isearch-printing-char
        kill-region
        yank-pop-forwards
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-paren
        isearch-abort
        ))
